/**
 * Kotil Skin Science — ₹99 consultation booking backend.
 * =============================================================================
 * Paste this into the "kotil@99" spreadsheet: Extensions ▸ Apps Script, replace
 * everything in Code.gs with this file, fill the two key lines below, then
 * Deploy ▸ New deployment ▸ Web app  (Execute as: Me · Who has access: Anyone).
 * Copy the /exec URL it gives you into CONSULT.appsScriptUrl in src/Consult.jsx.
 *
 * WHAT IS DIFFERENT FROM THE DEVRIZ ₹49 SCRIPT
 *
 * 1. The Razorpay keys are actually USED. The old script declared them and then
 *    wrote "Paid - ID: <whatever the browser sent>" without checking anything,
 *    so a row saying Paid only meant the browser claimed so. This one calls
 *    Razorpay's Payments API with the secret and confirms the payment really
 *    exists, really belongs to your account, and is really for ₹99, before the
 *    row is marked paid. That is why the secret lives here and never in the
 *    website's code — Apps Script runs on Google's servers, the site does not.
 *
 * 2. The row is written when the form is SUBMITTED, not when payment succeeds,
 *    and updated afterwards. Someone who fills in their name and number and
 *    then abandons the payment page is still a lead worth calling — the old
 *    script threw those away. They show up with Status "Started (not paid)".
 *
 * 3. The timestamp is formatted in Asia/Kolkata directly. The old script added
 *    5.5 hours to the clock AND then formatted it, which double-shifts the time
 *    whenever the script's own timezone is not UTC.
 *
 * The sheet tab and its header row are created automatically on first write.
 */

// ── YOUR RAZORPAY KEYS ───────────────────────────────────────────────────────
// Two ways to set these. Both work; the first is better.
//
// A) Script Properties (recommended). In this editor: ⚙ Project Settings ▸
//    Script properties ▸ Add script property, twice:
//        RAZORPAY_KEY_ID       rzp_live_…
//        RAZORPAY_KEY_SECRET   …
//    The secret then lives in the project's settings, not in the code — so it
//    is not in anything you copy, paste, screenshot or share, and a future edit
//    to this file can never leak it.
//
// B) Or just fill the two lines below and ignore the settings screen.
//    Fine, but then the secret is in the code — do not paste that code anywhere.
//
// Either way the secret stays on Google's servers. It must NEVER appear in
// src/Consult.jsx or anywhere else on the website: everything the browser
// downloads is public, and with the secret alone someone can issue refunds and
// read every payment on the account.
var RAZORPAY_KEY_ID     = "";   // rzp_live_… — the public key id
var RAZORPAY_KEY_SECRET = "";   // the matching secret
// ─────────────────────────────────────────────────────────────────────────────

/** Script Property if one is set, otherwise the var above. */
function prop_(name, fallback) {
  try {
    return PropertiesService.getScriptProperties().getProperty(name) || fallback;
  } catch (err) {
    return fallback;   // no properties service (rare) — fall back to the var
  }
}
function keyId_()     { return prop_("RAZORPAY_KEY_ID", RAZORPAY_KEY_ID); }
function keySecret_() { return prop_("RAZORPAY_KEY_SECRET", RAZORPAY_KEY_SECRET); }

// Leave BLANK if this script lives inside the kotil@99 spreadsheet itself
// (Extensions ▸ Apps Script) — it finds the sheet on its own.
// Only needed if you created the script standalone at script.google.com, in
// which case there is no "active" spreadsheet and every write fails with
// "Cannot read properties of null". Paste the long id out of the sheet's URL:
//   docs.google.com/spreadsheets/d/  THIS BIT  /edit
var SPREADSHEET_ID = "";

var SHEET_NAME   = "Bookings";   // tab inside the kotil@99 spreadsheet
var AMOUNT_PAISE = 9900;         // ₹99. Razorpay counts in paise — 99 * 100.
var TZ           = "Asia/Kolkata";

// Column order. Change it here and the whole script follows — every write looks
// columns up by name, so nothing breaks if you insert one in the middle.
var HEADERS = [
  "Timestamp",        // when the form was submitted
  "Booking ID",       // KS-… , generated by the website, unique per attempt
  "Name",
  "Mobile",           // +91XXXXXXXXXX — tap to call straight from the sheet
  "Concern",
  "Preferred time",
  "Status",           // Started (not paid) → Paid → or a verification failure
  "Payment ID",       // pay_… — searchable in the Razorpay dashboard
  "Amount",
  "Verified",         // what Razorpay itself said when we asked
  "Method",           // upi / card / netbanking, straight from Razorpay
  "Paid at",
  "Source",
  "utm_source",
  "utm_campaign"
];

/* ===========================================================================
   ROUTING
   ======================================================================== */

/** Visit the /exec URL in a browser — if you see this, the deployment is live. */
function doGet(e) {
  return respond({
    status: "ok",
    message: "Kotil ₹99 consultation backend is running",
    keysConfigured: !!(keyId_() && keySecret_()),
    sheet: SHEET_NAME
  });
}

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return respond({ success: false, error: "No data received." });
    }
    var data = JSON.parse(e.postData.contents);
    Logger.log("Action: " + data.action + " | Booking: " + data.bookingId);

    if (data.action === "lead")        return handleLead(data);
    if (data.action === "paid")        return handlePaid(data);
    if (data.action === "createOrder") return handleCreateOrder(data);

    return respond({ success: false, error: "Unknown action: " + data.action });
  } catch (err) {
    Logger.log("doPost error: " + err);
    return respond({ success: false, error: String(err) });
  }
}

/* ===========================================================================
   ROUTE 1 — the form was submitted (payment has NOT happened yet)
   ======================================================================== */

function handleLead(data) {
  try {
    var sheet = getSheet_();
    var row = blankRow_();
    set_(row, "Timestamp", stamp_());
    set_(row, "Booking ID", data.bookingId || "");
    set_(row, "Name", data.name || "");
    // Leading apostrophe: without it Sheets reads +919871054183 as a formula
    // and shows #ERROR!, which is exactly the cell a counsellor needs to dial.
    set_(row, "Mobile", data.phone ? "'" + data.phone : "");
    set_(row, "Concern", data.concern || "");
    set_(row, "Preferred time", data.slot || "");
    set_(row, "Status", "Started (not paid)");
    set_(row, "Amount", "Rs." + (AMOUNT_PAISE / 100));
    set_(row, "Source", data.source || "");
    set_(row, "utm_source", data.utm_source || "");
    set_(row, "utm_campaign", data.utm_campaign || "");
    sheet.appendRow(row);

    return respond({ success: true, bookingId: data.bookingId || "" });
  } catch (err) {
    Logger.log("handleLead error: " + err);
    return respond({ success: false, error: String(err) });
  }
}

/* ===========================================================================
   ROUTE 2 — Razorpay says the payment went through. Check that ourselves.
   ======================================================================== */

function handlePaid(data) {
  // A lock, because this both READS and WRITES a specific row. Two people
  // paying in the same second could otherwise find the same empty slot and one
  // would overwrite the other. appendRow alone would be safe; find-then-update
  // is not.
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(20000);
  } catch (err) {
    Logger.log("Could not get lock: " + err);
  }

  try {
    var paymentId = data.paymentId || "";
    var check     = verifyPayment_(paymentId);
    var sheet     = getSheet_();
    var rowIndex  = findRow_(sheet, "Booking ID", data.bookingId);

    var status =
      !check.checked ? "Paid (unverified — keys not set in Apps Script)"
      : check.ok     ? "Paid"
                     : "NEEDS CHECKING — " + check.reason;

    if (rowIndex > 0) {
      // The lead row already exists from the form submit; fill in the rest.
      writeCell_(sheet, rowIndex, "Status", status);
      writeCell_(sheet, rowIndex, "Payment ID", paymentId);
      writeCell_(sheet, rowIndex, "Verified", check.detail);
      writeCell_(sheet, rowIndex, "Method", check.method || "");
      writeCell_(sheet, rowIndex, "Paid at", stamp_());
      if (check.amount) writeCell_(sheet, rowIndex, "Amount", "Rs." + (check.amount / 100));
    } else {
      // No matching row — the lead call never landed (flaky network on the
      // phone, most likely). The money is real, so never drop it: write a
      // complete row from what the payment confirmation carried.
      var row = blankRow_();
      set_(row, "Timestamp", stamp_());
      set_(row, "Booking ID", data.bookingId || "");
      set_(row, "Name", data.name || "");
      set_(row, "Mobile", data.phone ? "'" + data.phone : "");
      set_(row, "Concern", data.concern || "");
      set_(row, "Preferred time", data.slot || "");
      set_(row, "Status", status);
      set_(row, "Payment ID", paymentId);
      set_(row, "Amount", "Rs." + ((check.amount || AMOUNT_PAISE) / 100));
      set_(row, "Verified", check.detail);
      set_(row, "Method", check.method || "");
      set_(row, "Paid at", stamp_());
      set_(row, "Source", data.source || "");
      set_(row, "utm_source", data.utm_source || "");
      set_(row, "utm_campaign", data.utm_campaign || "");
      sheet.appendRow(row);
    }

    Logger.log("Paid: " + data.bookingId + " | " + paymentId + " | " + status);
    return respond({ success: true, verified: !!check.ok, status: status });

  } catch (err) {
    Logger.log("handlePaid error: " + err);
    return respond({ success: false, error: String(err) });
  } finally {
    try { lock.releaseLock(); } catch (ignore) {}
  }
}

/**
 * Ask Razorpay whether this payment is real, is ours, and is for ₹99.
 *
 * This is the whole reason the secret lives in Apps Script. Anyone can POST
 * {"action":"paid","paymentId":"pay_fake"} at the web app URL — only this call
 * can tell that apart from a genuine booking.
 */
function verifyPayment_(paymentId) {
  if (!paymentId) {
    return { checked: true, ok: false, reason: "no payment id sent", detail: "No payment id" };
  }
  if (!keyId_() || !keySecret_()) {
    return { checked: false, detail: "Not checked — Razorpay keys are blank in Apps Script" };
  }

  try {
    var res = UrlFetchApp.fetch(
      "https://api.razorpay.com/v1/payments/" + encodeURIComponent(paymentId),
      {
        method: "get",
        headers: {
          Authorization: "Basic " + Utilities.base64Encode(keyId_() + ":" + keySecret_())
        },
        muteHttpExceptions: true
      }
    );

    var code = res.getResponseCode();
    if (code !== 200) {
      // 400/404 = no such payment on this account. 401 = wrong key or secret.
      return {
        checked: true, ok: false,
        reason: "Razorpay returned " + code,
        detail: "Razorpay returned " + code + " — " + res.getContentText().slice(0, 180)
      };
    }

    var p       = JSON.parse(res.getContentText());
    var settled = (p.status === "captured" || p.status === "authorized");
    var correct = Number(p.amount) === AMOUNT_PAISE;

    if (!settled) {
      return { checked: true, ok: false, reason: "payment status is " + p.status,
               detail: "Razorpay status: " + p.status, method: p.method, amount: p.amount };
    }
    if (!correct) {
      return { checked: true, ok: false,
               reason: "amount was Rs." + (p.amount / 100) + ", expected Rs." + (AMOUNT_PAISE / 100),
               detail: "Wrong amount: Rs." + (p.amount / 100), method: p.method, amount: p.amount };
    }

    return {
      checked: true, ok: true,
      detail: "Confirmed by Razorpay (" + p.status + ")",
      method: p.method, amount: p.amount
    };

  } catch (err) {
    // A network blip must not lose the booking — flag it for a human instead.
    Logger.log("verifyPayment_ error: " + err);
    return { checked: true, ok: false, reason: "could not reach Razorpay",
             detail: "Verification failed: " + String(err).slice(0, 180) };
  }
}

/* ===========================================================================
   ROUTE 3 — optional: create a Razorpay order before checkout opens
   ===========================================================================
   Only needed if your Razorpay account has "Orders API mandatory" switched on,
   in which case Checkout refuses a payment that has no order_id. The Devriz
   ₹49 flow does not use orders, so Kotil almost certainly does not need this —
   but if payments start failing with "order_id is required", set
   `useOrders: true` in CONSULT (src/Consult.jsx) and this route takes over.
   It costs one extra round trip before the payment sheet appears, which is why
   it is off by default.
   ======================================================================== */

function handleCreateOrder(data) {
  try {
    if (!keyId_() || !keySecret_()) {
      return respond({ success: false, error: "Razorpay keys are blank in Apps Script." });
    }

    var res = UrlFetchApp.fetch("https://api.razorpay.com/v1/orders", {
      method: "post",
      contentType: "application/json",
      headers: {
        Authorization: "Basic " + Utilities.base64Encode(keyId_() + ":" + keySecret_())
      },
      payload: JSON.stringify({
        amount: AMOUNT_PAISE,
        currency: "INR",
        receipt: data.bookingId || "",
        notes: { name: data.name || "", phone: data.phone || "", concern: data.concern || "" }
      }),
      muteHttpExceptions: true
    });

    if (res.getResponseCode() !== 200) {
      return respond({ success: false, error: "Razorpay: " + res.getContentText().slice(0, 200) });
    }

    var order = JSON.parse(res.getContentText());
    return respond({ success: true, orderId: order.id, amount: order.amount, currency: order.currency });

  } catch (err) {
    Logger.log("handleCreateOrder error: " + err);
    return respond({ success: false, error: String(err) });
  }
}

/* ===========================================================================
   SHEET HELPERS
   ======================================================================== */

/** The Bookings tab, created with a frozen, formatted header row if missing. */
function getSheet_() {
  var ss = SPREADSHEET_ID
    ? SpreadsheetApp.openById(SPREADSHEET_ID)
    : SpreadsheetApp.getActiveSpreadsheet();

  if (!ss) {
    throw new Error(
      "No spreadsheet found. This script is not bound to kotil@99 — either " +
      "recreate it from the sheet (Extensions > Apps Script), or paste the " +
      "sheet id into SPREADSHEET_ID at the top of this file."
    );
  }

  var sheet = ss.getSheetByName(SHEET_NAME) || ss.insertSheet(SHEET_NAME);

  if (sheet.getLastRow() === 0) {
    sheet.appendRow(HEADERS);
    sheet.getRange(1, 1, 1, HEADERS.length)
      .setFontWeight("bold")
      .setBackground("#0d1b2a")
      .setFontColor("#f4c563");
    sheet.setFrozenRows(1);
    sheet.setColumnWidth(1, 150);   // Timestamp
    sheet.setColumnWidth(4, 130);   // Mobile
    sheet.setColumnWidth(8, 180);   // Payment ID
  }

  // Force the Mobile column to plain text. Belt and braces with the leading
  // apostrophe in handleLead: Sheets will happily turn +919871054183 into the
  // number 919871054183, and a counsellor cannot dial that.
  sheet.getRange(1, col_("Mobile") + 1, sheet.getMaxRows(), 1).setNumberFormat("@");

  return sheet;
}

function col_(name) {
  var i = HEADERS.indexOf(name);
  if (i < 0) throw new Error("No such column: " + name);
  return i;                                    // 0-based, for the row array
}

function blankRow_() {
  var row = [];
  for (var i = 0; i < HEADERS.length; i++) row.push("");
  return row;
}

function set_(row, name, value) {
  row[col_(name)] = value;
}

function writeCell_(sheet, rowIndex, name, value) {
  sheet.getRange(rowIndex, col_(name) + 1).setValue(value);
}

/** 1-based sheet row whose `name` column equals `value`, or -1. */
function findRow_(sheet, name, value) {
  if (!value) return -1;
  var last = sheet.getLastRow();
  if (last < 2) return -1;
  var values = sheet.getRange(2, col_(name) + 1, last - 1, 1).getValues();
  for (var i = values.length - 1; i >= 0; i--) {     // newest first
    if (String(values[i][0]).trim() === String(value).trim()) return i + 2;
  }
  return -1;
}

function stamp_() {
  return Utilities.formatDate(new Date(), TZ, "dd MMM yyyy, hh:mm a");
}

function respond(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

/* ===========================================================================
   TESTS — run these from the Apps Script editor before going live
   ======================================================================== */

/**
 * 0. Why does /exec say keysConfigured:false?
 *
 * Run this and read the Execution log. It prints every property name it can
 * see and a masked prefix of each value, so a typo or a stray space shows up
 * without ever printing the secret.
 *
 * THE USUAL CAUSE: a web app serves a SNAPSHOT of the code from the moment you
 * deployed. Script Properties are read at runtime and need no redeploy — but
 * only if the deployed snapshot already contains the prop_() helper. If you
 * pasted this version of the file AFTER deploying, /exec is still running the
 * older code that only reads the two vars, and it will report false forever.
 * Fix: Deploy > Manage deployments > pencil > Version: New version > Deploy.
 * That keeps the same URL.
 */
function testKeys() {
  var mask = function (v) {
    if (!v) return "(empty)";
    return v.slice(0, 8) + "…" + v.length + " chars";
  };
  var all = {};
  try {
    all = PropertiesService.getScriptProperties().getProperties();
  } catch (err) {
    Logger.log("PropertiesService threw: " + err);
  }
  var names = Object.keys(all);

  Logger.log("Script properties found: " + (names.length ? names.join(", ") : "NONE"));
  names.forEach(function (n) {
    Logger.log("  [" + n + "] = " + mask(all[n]) +
               (n !== n.trim() ? "   <-- NAME HAS A LEADING/TRAILING SPACE" : ""));
  });
  Logger.log("");
  Logger.log("var RAZORPAY_KEY_ID     in code = " + mask(RAZORPAY_KEY_ID));
  Logger.log("var RAZORPAY_KEY_SECRET in code = " + mask(RAZORPAY_KEY_SECRET));
  Logger.log("");
  Logger.log("keyId_()     resolves to = " + mask(keyId_()));
  Logger.log("keySecret_() resolves to = " + mask(keySecret_()));
  Logger.log("");
  Logger.log(keyId_() && keySecret_()
    ? "OK — this code can see both keys. If /exec still says false, the DEPLOYMENT "
      + "is an older snapshot: Deploy > Manage deployments > pencil > New version."
    : "NOT SET — add script properties named exactly RAZORPAY_KEY_ID and "
      + "RAZORPAY_KEY_SECRET (case sensitive, no spaces), or fill the two vars.");
}

/** 1. Does the script reach the sheet? Writes one obvious test row. */
function testSheetWrite() {
  handleLead({
    bookingId: "KS-TEST-0000", name: "Test User", phone: "+919999999999",
    concern: "acne", slot: "Morning · 10–1", source: "apps script editor test"
  });
  Logger.log("Wrote a test lead row. Check the " + SHEET_NAME + " tab.");
}

/**
 * 2. Are the Razorpay keys right? Paste any REAL payment id from your Razorpay
 *    dashboard (Transactions ▸ Payments) and run this.
 *    - "Confirmed by Razorpay"  → keys are correct
 *    - "Razorpay returned 401"  → key id and secret do not match
 *    - "Razorpay returned 400"  → that payment is not on this account
 */
function testRazorpayKeys() {
  var PASTE_A_REAL_PAYMENT_ID_HERE = "pay_xxxxxxxxxxxxxx";
  Logger.log(JSON.stringify(verifyPayment_(PASTE_A_REAL_PAYMENT_ID_HERE), null, 2));
}

/** 3. End to end, minus the money: leaves a NEEDS CHECKING row, which is the
 *     correct result for a fake payment id. Delete the row afterwards. */
function testFullFlow() {
  var id = "KS-TEST-" + Math.floor(Math.random() * 9000 + 1000);
  handleLead({ bookingId: id, name: "Flow Test", phone: "+919999999999",
               concern: "pigment", slot: "Evening · 4–7", source: "flow test" });
  handlePaid({ bookingId: id, paymentId: "pay_fake0000000000",
               name: "Flow Test", phone: "+919999999999" });
  Logger.log("Look for " + id + " — it should say NEEDS CHECKING, not Paid.");
}
