import AVIF_URLS from '../avif-manifest.json'

// Which WebP URLs have an AVIF twin worth serving. Generated by
// `npm run assets:avif` — see scripts/avif.mjs for why some are left out.
const HAS_AVIF = new Set(AVIF_URLS)

/**
 * The one <img> the site uses.
 *
 * - Serves AVIF (~40% smaller than our WebP) where one exists, WebP otherwise.
 * - Lazy + async-decoded by default, because almost every image here is below
 *   the fold. Pass `eager` for the few that are not — that also flips
 *   fetchPriority to high so it races ahead of the JS bundle.
 * - width/height are strongly encouraged: they reserve the box and stop the
 *   layout shifting as each image lands.
 */
export default function Img({ src, alt = '', eager = false, className, ...rest }) {
  const img = (
    <img
      src={src}
      alt={alt}
      className={className}
      loading={eager ? 'eager' : 'lazy'}
      decoding={eager ? 'sync' : 'async'}
      {...(eager ? { fetchPriority: 'high' } : {})}
      {...rest}
    />
  )

  if (!HAS_AVIF.has(src)) return img

  // <picture> must carry the class when one is set, since the CSS targets the
  // img itself in most rules — keep the class on the img and leave the wrapper
  // transparent to layout via CSS (picture { display: contents }).
  return (
    <picture>
      <source srcSet={src.replace(/\.webp$/, '.avif')} type="image/avif" />
      {img}
    </picture>
  )
}
